# Generated by Django 4.2 on 2024-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('sex', models.BooleanField(verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'герой',
                'verbose_name_plural': 'герои',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('sex', models.CharField(choices=[('Папа', 'Папа'), ('Мама', 'Мама')], default='Мама', max_length=50, verbose_name='Пол')),
                ('phone', models.PositiveBigIntegerField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'родитель',
                'verbose_name_plural': 'родители',
            },
        ),
    ]
