# Generated by Django 4.2 on 2024-09-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='sex',
            field=models.CharField(choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')], max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='sex',
            field=models.CharField(choices=[('Папа', 'Папа'), ('Мама', 'Мама'), ('Бабушка', 'Бабушка'), ('Дедушка', 'Дедушка'), ('Вожатая класса', 'Вожатая класса')], default='Мама', max_length=50, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Мощный', 'Мощный'), ('Отважный', 'Отважный'), ('Отряд мам', 'Отряд мам'), ('Пред.командир', 'Пред.командир'), ('Командир', 'Командир'), ('Выбыл', 'Выбыл')], max_length=50, verbose_name='Вид отряда')),
                ('start_from', models.DateField(verbose_name='с')),
                ('stop_at', models.DateField(blank=True, null=True, verbose_name='по')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.hero', verbose_name='Герой')),
            ],
            options={
                'verbose_name': 'отряд',
                'verbose_name_plural': 'отряды',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Сила Дружбы', 'Сила Дружбы'), ('Школа Мам', 'Школа Мам'), ('Институт', 'Институт'), ('Вожатая', 'Вожатая'), ('Гостевой', 'Гостевой'), ('Выбыли', 'Выбыли'), ('Наставник', 'Наставник'), ('Стажёр', 'Стажёр'), ('Интересуется', 'Интересуется'), ('Не интересуется', 'Не интересуется')], max_length=50, verbose_name='Вид программы')),
                ('start_from', models.DateField(verbose_name='с')),
                ('stop_at', models.DateField(blank=True, null=True, verbose_name='по')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'программа',
                'verbose_name_plural': 'программы',
            },
        ),
    ]
