# Generated by Django 4.2 on 2024-09-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_alter_hero_sex_alter_parent_sex_team_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='HeroStatus',
        ),
        migrations.RenameModel(
            old_name='Program',
            new_name='ParentStatus',
        ),
        migrations.AlterModelOptions(
            name='herostatus',
            options={'verbose_name': 'статус героя', 'verbose_name_plural': 'статусы героев'},
        ),
        migrations.AlterModelOptions(
            name='parentstatus',
            options={'verbose_name': 'статус родителя', 'verbose_name_plural': 'статусы родителей'},
        ),
    ]
