# Generated by Django 4.2 on 2024-09-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_hero_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Город (локация)')),
                ('day_time', models.CharField(choices=[('сб 09:00', 'сб 09:00'), ('сб 15:00', 'сб 15:00'), ('вс 09:00', 'вс 09:00'), ('вс 15:00', 'вс 15:00')], max_length=50, verbose_name='Дата и время тренировки')),
            ],
            options={
                'verbose_name': 'ячейка',
                'verbose_name_plural': 'ячейки',
            },
        ),
        migrations.AddField(
            model_name='herostatus',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.cell', verbose_name='Ячейка'),
        ),
        migrations.AddField(
            model_name='parentstatus',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.cell', verbose_name='Ячейка'),
        ),
    ]
