# Generated by Django 4.2 on 2024-09-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_cell_herostatus_cell_parentstatus_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.cell', verbose_name='Ячейка')),
                ('heroes', models.ManyToManyField(to='heroes.hero', verbose_name='Явка героев')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.parent', verbose_name='Наставник')),
            ],
            options={
                'verbose_name': 'тренировка',
                'verbose_name_plural': 'тренировки',
            },
        ),
    ]
