# Generated by Django 4.2 on 2024-09-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Вид платежа')),
                ('value', models.PositiveIntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'абонемент',
                'verbose_name_plural': 'абонементы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата оплаты')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.parent', verbose_name='Родитель')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.paymenttype', verbose_name='Вид платежа')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
