# Generated by Django 4.2 on 2024-09-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_paymenttype_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostatus',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.parent', verbose_name='Наставник'),
        ),
    ]
